/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    DefaultLayout: typeof import('@/layout/componets/DefaultLayout.vue')['default']
    Hello: typeof import('./src/components/Hello.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Introduce: typeof import('@/layout/componets/Introduce.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    Navigate: typeof import('./src/components/Navigate.vue')['default']
    Navigate2: typeof import('./src/components/Navigate2.vue')['default']
    RegisterForm: typeof import('./src/components/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskManager: typeof import('./src/components/TaskManager.vue')['default']
    TaskTimeline: typeof import('./src/components/TaskTimeline.vue')['default']
    Vbar: typeof import('./src/components/Vbar.vue')['default']
  }
}
